# Generated by Django 4.2.4 on 2023-08-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("product", "0002_alter_product_conditions_alter_product_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="user.sellerprofile",
                verbose_name="Product seller",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
