# Generated by Django 4.2.4 on 2023-08-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_seller_profile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "verbose_name": "Product type",
                "verbose_name_plural": "Products type",
            },
        ),
        migrations.AlterField(
            model_name="profitprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profit_prices",
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
