# Generated by Django 4.2.4 on 2023-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_producttype_options_alter_profitprice_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=150, null=True, unique=True
            ),
        ),
    ]
