# Generated by Django 4.2.4 on 2023-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
