# Generated by Django 4.2.4 on 2023-09-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("product", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="user.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="common.card",
                verbose_name="Card",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="user.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="product.producttype",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="user.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "profile")},
        ),
    ]
